<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Справочник;)</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="/template/css/templatemo_style.css" rel="stylesheet" type="text/css" />
    <!-- templatemo 358 carousel -->
    <!--
    Carousel Template
    http://www.templatemo.com/preview/templatemo_358_carousel
    -->
    <script type="text/javascript" src="/template/js/jquery-1-4-2.min.js"></script>
    <!--script type="text/javascript" src="/jqueryui/js/jquery-ui-1.7.2.custom.min.js"></script-->
    <script type="text/javascript" src="/template/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/template/js/showhide.js"></script>
    <script type="text/JavaScript" src="/template/js/jquery.mousewheel.js"></script>

    <link rel="stylesheet" type="text/css" href="/template/css/ddsmoothmenu.css" />

    <script type="text/javascript" src="/template/js/jquery.min.js"></script>





    <script type="text/javascript" src="/template/js/ddsmoothmenu.js">

        /***********************************************
         * Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
         * This notice MUST stay intact for legal use
         * Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
         ***********************************************/

    </script>

    <script type="text/javascript">

        ddsmoothmenu.init({
            mainmenuid: "templatemo_menu", //menu DIV id
            orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
            classname: 'ddsmoothmenu', //class added to menu's outer DIV
            //customtheme: ["#1c5a80", "#18374a"],
            contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
        })

    </script>

    <!-- Load the CloudCarousel JavaScript file -->
    <script type="text/JavaScript" src="/template/js/cloud-carousel.1.0.5.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){

            // This initialises carousels on the container elements specified, in this case, carousel1.
            $("#carousel1").CloudCarousel(
                {
                    reflHeight: 40,
                    reflGap: 2,
                    titleBox: $('#da-vinci-title'),
                    altBox: $('#da-vinci-alt'),
                    buttonLeft: $('#slider-left-but'),
                    buttonRight: $('#slider-right-but'),
                    yRadius: 30,
                    xPos: 480,
                    yPos: 32,
                    speed:0.15,
                    autoRotate: "yes",
                    autoRotateDelay: 1500
                }
            );
        });

    </script>

</head>

<body id="home">

<div id="templatemo_header_wrapper">
    <div style="display: inline-block; margin: -40px 0 0 800px; font-size: 14px; color: #4A73A7 ">
        <ul style="display: inline-block; font-size: 12px">
            <?php if (User::isGuest()): ?>
                <li style="display: inline-block"><a style="color: #4A73A7" href="/user/register/">Регистрация</a></li>
                <li style="display: inline-block"><a style="color: #4A73A7" href="/user/login/">Вход</a></li>
            <?php else: ?>
                <li style="display: inline-block"><a style="color: #4A73A7" href="/cabinet/">Аккаунт</a></li>
                <li style="display: inline-block"><a style="color: #4A73A7" href="/user/logout/">Выход</a></li>
            <?php endif ?>
        </ul>
        <div class="cleaner"></div>
    </div><br>
    <div id="site_title"><h1><a href="/">Справочник;)</a></h1></div>

    <div id="templatemo_menu" class="ddsmoothmenu">
        <ul>
            <?php $menu = Menu::getMenu(); ?>
            <?php foreach ($menu as  $m):?>
                <li><a class="<?php if ($m['link'] == $_SERVER['REQUEST_URI']) echo 'selected'?>" href="<?=$m['link']?>"><?=$m['name']?></a>
                    <?php if ($m['id'] == 4): ?>
                    <ul>
                        <li><span class="top"></span><span class="bottom"></span></li>
                        <?php $departments = Department::getDepartmentListWithLimit();?>
                        <?php foreach ($departments as  $departmentItem):?>
                            <li><a href="/department/<?=$departmentItem['id']?>"><?=$departmentItem['department']?></a></li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <br style="clear: left" />
    </div> <!-- end of templatemo_menu -->
    <div class="cleaner"></div>
</div>	<!-- END of templatemo_header_wrapper -->