<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Тег META, атрибут charset</title>

    <link href="/templates/css/1140.css" rel="stylesheet" type="text/css" />
    <link href="/templates/css/styles.css" rel="stylesheet" type="text/css" />

</head>
<body>
<p>Типовой документ.</p>
</body>
</html>
<body>

<div id="profiletabs" class="uitabs">

    <div id="upr_profile">
        <div class="column4 alpha">
            <div class="profile_menu">
                <div class="usr_avatar">
                    <img alt="Администратор" class="usr_img"
                         src="/templates/img/name.jpg"/>
                </div>
            </div>
        </div>
        <div class="column7 omega" style="margin-left:0">
            <div class="user_profile_data">
                <div class="field">
                    <div class="title">ФИО:</div>
                    <div class="value"><span class="logdate">Иванов Иван Иванович</span></div>
                </div>
                <div class="field">
                    <div class="title">Компания:</div>
                    <div class="value">
                        Конгресс
                    </div>
                </div>
                <div class="field">
                    <div class="title">Подразделение:</div>
                    <div class="value">
                        ИТ отдел
                    </div>
                </div>
                <div class="field">
                    <div class="title">Должность:</div>
                    <div class="value">
                        Программист
                    </div>
                </div>
                <div class="field">
                    <div class="title">Город:</div>
                    <div class="value"><a href="/users/city/%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0">Москва</a>, Россия
                    </div>
                </div>

                <div class="field">
                    <div class="title">Дата рождения:</div>
                    <div class="value">23 октября 1980</div>
                </div>

                <div class="field">
                    <div class="title">Пол:</div>
                    <div class="value">Мужской</div>
                </div>

                <div class="field">
                    <div class="title">Skype:</div>
                    <div class="value">100200300</div>
                </div>


                <div class="field">
                    <div class="title">E-mail:</div>
                    <div class="value"><a href="#" rel="ur/smc/nimda" class="email">admin@cms.ru</a></div>
                </div>

                <div class="field">
                    <div class="title">Телефон:</div>
                    <div class="value"><a href="#" rel="ur/smc/nimda" class="email">0679044455</a></div>
                </div>
                <div class="field">
                    <div class="title">Адрес:</div>
                    <div class="value"><a href="#" rel="ur/smc/nimda" class="email">Киев, ул. Крейсера, 5</a></div>
                </div>

                <script>
                    $('.email').nospam({replaceText: true});
                </script>

                <div class="field">
                    <div class="title">Образование:</div>
                    <div class="value">Высшее</div>
                </div>

</body>